# Generated by Django 4.1.1 on 2022-09-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='label',
            new_name='labels',
        ),
    ]
