# Generated by Django 4.1 on 2022-09-04 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='author',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
