# Generated by Django 4.1 on 2022-09-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_alter_labels_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labels',
            name='task',
        ),
    ]
