# Generated by Django 4.1 on 2022-09-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_remove_labels_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='label',
            field=models.ManyToManyField(related_name='tasks', to='task_manager.labels'),
        ),
    ]
